### ISSUE TITLE
作者大大

### ISSUE THREAD

**Issue by lisa-bear** [TaroXin/HermesEventBusDemo#1]
我才用你的demo可以正常运行，我自己写了一个简单的demo，发现无法接收到消息。
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        HermesEventBus.getDefault().register(this);
        setContentView(R.layout.test);
        m_info = (TextView) findViewById(R.id.info);
    }

    public void goToNext(View view) {
//        startActivity(new Intent(this, NextActivity.class));
//        HermesEventBus.getDefault().post("ziao"); //new NextMessage("我是NextMessage传递的信息")
        HermesEventBus.getDefault().post("This is an event from the main process.");
    }

    @Subscribe(threadMode = ThreadMode.MAIN)
    public void showText(String text) {
        m_info.setText(text);
        Log.v("EricZhao", "MainActivity receives an event: " + text);
    }

    @Override
    protected void onDestroy() {
        // unregister
        HermesEventBus.getDefault().unregister(this);
        super.onDestroy();
    }
帮忙看下，谢谢

**Comment by TaroXin** [comment]
接收事件必须是先订阅，才可以使用 post 发送事件，如果依旧不能接收事件，建议将订阅事件参数类型换成实体类进行传递，post事件不能先于订阅事件执行，注意你的 post 时间的执行时机
